export interface ChildrenData {
    id: string,
    avatar: any,
    pictures: any,
    fullName: string,
    birthDay: string,
    gender: string,
    nation: string,
    address: string,
    joinDate: string,
    status: string,
    note: string,
    classRoom: string,
    parentName: string,
    phone: string,
}